[package]
name = "spmd"
version = "0.1.0"
authors = ["gnzlbg <gonzalobg88@gmail.com>"]

[dependencies]
cfg-if = "^0.1"

[dev-dependencies]
interpolate_idents = "^0.2"
arrayvec = { version = "^0.4", default-features = false }